import { world } from './state.js';
import { FACTIONS } from './factions.js';
import { createCloudClusterRegistry, ensureRegistry as ensureCloudClusterRegistry } from './cloudCluster/registry.js';
import { createCluster as createCloudCluster } from './cloudCluster/domain/cluster.js';
import { computeOwnershipEntries } from './factoryOwnership/transform/index.js';
import { createClusterRuntime } from './factoryOwnership/runtime/clusterRuntime.js';

export function createFactoryOwnershipManager({
  ensureFactoryState,
  factoryKindMeta,
  factoryItemLabel,
  getRecipeInputMap,
  getBioforgeRecipe,
  defaultBioforgeRecipe,
  getConstructorBlueprint,
  defaultConstructorBlueprint,
  FactoryKind,
}){
  const {
    ensureFactoryCloudRegistry,
    snapshotRegistry,
    synchronizeFactionCluster,
  } = createClusterRuntime({
    factoryKindMeta,
    factoryItemLabel,
    getRecipeInputMap,
    getBioforgeRecipe,
    defaultBioforgeRecipe,
    getConstructorBlueprint,
    defaultConstructorBlueprint,
    FactoryKind,
  });

  function captureOwnershipInputs(factory){
    const worldSnapshot = {
      width: Number.isFinite(world?.W) ? world.W : 0,
      dominantFaction: world?.dominantFaction ?? [],
      controlLevel: world?.controlLevel ?? [],
    };

    const nodes = [];
    const nodesByTile = new Map();
    if(factory?.nodes instanceof Map){
      for(const [key, node] of factory.nodes.entries()){
        const tileIdx = Number(key);
        if(!Number.isFinite(tileIdx) || tileIdx < 0) continue;
        const nodeSnapshot = {
          tileIdx,
          resource: node?.resource ?? null,
        };
        nodes.push(nodeSnapshot);
        nodesByTile.set(tileIdx, nodeSnapshot);
      }
    }

    const structures = [];
    const structuresByTile = new Map();
    if(factory?.structures instanceof Map){
      for(const [key, structure] of factory.structures.entries()){
        const tileIdx = Number(key);
        if(!Number.isFinite(tileIdx) || tileIdx < 0) continue;
        const structureSnapshot = {
          tileIdx,
          kind: structure?.kind ?? null,
          orientation: structure?.orientation ?? null,
          recipeKey: structure?.recipeKey ?? null,
          availableRecipeKeys: Array.isArray(structure?.availableRecipeKeys) ? structure.availableRecipeKeys.slice() : null,
          activeRecipeIndex: typeof structure?.activeRecipeIndex === 'number' ? structure.activeRecipeIndex : null,
          blueprintKey: structure?.blueprintKey ?? null,
          availableBlueprintKeys: Array.isArray(structure?.availableBlueprintKeys) ? structure.availableBlueprintKeys.slice() : null,
        };
        structures.push(structureSnapshot);
        structuresByTile.set(tileIdx, structureSnapshot);
      }
    }

    return {
      world: worldSnapshot,
      nodes,
      structures,
      nodesByTile,
      structuresByTile,
      registrySnapshot: snapshotRegistry(factory),
      manualReservations: captureManualReservations(factory),
    };
  }

  function captureManualReservations(factory){
    if(factory?.manualReservations && Array.isArray(factory.manualReservations)){
      return factory.manualReservations.map((reservation) => ({ ...reservation }));
    }
    return [];
  }

  function clusterIdForFaction(factionId){
    return `faction-${factionId}-cloud`;
  }

  function clusterLabelForFaction(faction){
    if(!faction) return 'Faction Cloud';
    const key = faction.key ?? faction.id ?? '?';
    return `Faction ${key} Cloud`;
  }

  function ensureFactionCloudCluster(factory, faction, registry = ensureFactoryCloudRegistry(factory)){
    const clusterId = clusterIdForFaction(faction.id);
    let cluster = registry.byId.get(clusterId);
    if(!cluster){
      cluster = createCloudCluster({
        id: clusterId,
        name: clusterLabelForFaction(faction),
        description: `Autogenerated cluster for faction ${faction.key ?? faction.id}.`,
        metadata: {
          factionId: faction.id,
          factionKey: faction.key ?? null,
          auto: true,
        },
        objects: [],
        links: [],
      });
      registry.byId.set(clusterId, cluster);
    }
    if(!registry.order.includes(clusterId)){
      registry.order.push(clusterId);
    }
    return cluster;
  }

  function removeFactionCloudCluster(factory, factionId, registry = ensureFactoryCloudRegistry(factory)){
    const clusterId = clusterIdForFaction(factionId);
    if(!registry.byId.delete(clusterId)){
      return false;
    }
    const orderIndex = registry.order.indexOf(clusterId);
    if(orderIndex >= 0){
      registry.order.splice(orderIndex, 1);
    }
    return true;
  }

  function syncFactionCloudClusters(factory, ownershipByFaction, ownershipInputs){
    if(!factory) return [];
    const registry = ensureFactoryCloudRegistry(factory);
    if(!(ownershipByFaction instanceof Map)){
      ownershipByFaction = factory.ownershipByFaction instanceof Map ? factory.ownershipByFaction : new Map();
    }
    const bundles = [];
    const manualLinkReconciliation = new Map();
    const manualLinkWarnings = [];
    for(const faction of FACTIONS){
      const clusterId = clusterIdForFaction(faction.id);
      const entries = ownershipByFaction.get(faction.id) ?? [];
      let cluster = registry.byId.get(clusterId);
      if(entries.length > 0){
        cluster = ensureFactionCloudCluster(factory, faction, registry);
        const result = synchronizeFactionCluster({
          cluster,
          entries,
          factory,
          registry,
          ownershipInputs,
        });
        if(result?.diffBundle){
          bundles.push({
            factionId: faction.id,
            clusterId,
            bundle: result.diffBundle,
          });
        }
        if(result?.manualLinkReconciliation){
          manualLinkReconciliation.set(clusterId, result.manualLinkReconciliation);
          if(Array.isArray(result.manualLinkReconciliation.droppedLinks) && result.manualLinkReconciliation.droppedLinks.length){
            manualLinkWarnings.push({
              factionId: faction.id,
              clusterId,
              droppedLinks: result.manualLinkReconciliation.droppedLinks,
            });
          }
        }
        continue;
      }
      if(!cluster) continue;
      const result = synchronizeFactionCluster({
        cluster,
        entries,
        factory,
        registry,
        ownershipInputs,
      });
      if(result?.diffBundle){
        bundles.push({
          factionId: faction.id,
          clusterId,
          bundle: result.diffBundle,
        });
      }
      if(result?.manualLinkReconciliation){
        manualLinkReconciliation.set(clusterId, result.manualLinkReconciliation);
        if(Array.isArray(result.manualLinkReconciliation.droppedLinks) && result.manualLinkReconciliation.droppedLinks.length){
          manualLinkWarnings.push({
            factionId: faction.id,
            clusterId,
            droppedLinks: result.manualLinkReconciliation.droppedLinks,
          });
        }
      }
      const hasObjects = (cluster.objects?.size ?? 0) > 0;
      const hasLinks = (cluster.links?.size ?? 0) > 0;
      if(!hasObjects && !hasLinks){
        removeFactionCloudCluster(factory, faction.id, registry);
      }
    }
    factory.manualLinkReconciliation = manualLinkReconciliation;
    factory.manualLinkWarnings = manualLinkWarnings;
    if(Array.isArray(manualLinkWarnings) && manualLinkWarnings.length){
      factory.manualLinkWarningsLog = manualLinkWarnings;
    } else if(!Array.isArray(factory.manualLinkWarningsLog)){
      factory.manualLinkWarningsLog = [];
    }
    return bundles;
  }

  function refreshFactoryOwnership(){
    const factory = ensureFactoryState();
    const snapshot = captureOwnershipInputs(factory);
    const { entries, byFaction, unassigned } = computeOwnershipEntries(snapshot);

    factory.ownershipRecords = entries;
    factory.ownershipByFaction = byFaction;
    factory.unassignedOwnership = unassigned;
    factory.ownershipDiffBundles = syncFactionCloudClusters(factory, byFaction, snapshot);
    return factory.ownershipDiffBundles;
  }

  function cloneOwnershipEntry(entry){
    if(!entry) return null;
    const clone = {
      id: entry.id,
      tileIdx: entry.tileIdx,
      type: entry.type,
      kind: entry.kind,
      control: entry.control,
      factionId: entry.factionId,
      dominantFactionId: entry.dominantFactionId ?? null,
    };
    if(entry.coords){
      clone.coords = { ...entry.coords };
    }
    if(entry.resource != null) clone.resource = entry.resource;
    if(entry.orientation != null) clone.orientation = entry.orientation;
    return clone;
  }

  function getFactoryOwnership(){
    refreshFactoryOwnership();
    const factory = ensureFactoryState();
    const byFactionMap = factory.ownershipByFaction instanceof Map ? factory.ownershipByFaction : new Map();
    const allEntries = Array.isArray(factory.ownershipRecords) ? factory.ownershipRecords : [];
    const unassigned = Array.isArray(factory.unassignedOwnership) ? factory.unassignedOwnership : [];
    const manualLinkWarnings = Array.isArray(factory.manualLinkWarningsLog)
      ? factory.manualLinkWarningsLog
      : Array.isArray(factory.manualLinkWarnings)
        ? factory.manualLinkWarnings
        : [];
    const manualLinkReconciliation = factory.manualLinkReconciliation instanceof Map
      ? Array.from(factory.manualLinkReconciliation.entries(), ([clusterId, reconciliation]) => ({
        clusterId,
        reconciliation,
      }))
      : [];
    const byFaction = FACTIONS.map((faction) => ({
      factionId: faction.id,
      factionKey: faction.key,
      color: faction.color,
      objects: (byFactionMap.get(faction.id) ?? []).map(cloneOwnershipEntry).filter(Boolean),
    }));
    return {
      byFaction,
      unassigned: unassigned.map(cloneOwnershipEntry).filter(Boolean),
      all: allEntries.map(cloneOwnershipEntry).filter(Boolean),
      diffBundles: Array.isArray(factory.ownershipDiffBundles) ? factory.ownershipDiffBundles : [],
      manualLinkWarnings,
      manualLinkReconciliation,
    };
  }

  return {
    refreshFactoryOwnership,
    getFactoryOwnership,
    ensureFactoryCloudRegistry,
  };
}

export function initialiseFactoryOwnership(factory){
  const registry = ensureCloudClusterRegistry(factory?.cloudClusters);
  if(factory){
    factory.cloudClusters = registry ?? createCloudClusterRegistry();
  }
  return registry;
}
