import { world } from './state.js';
import { FACTIONS } from './factions.js';
import { createCloudClusterRegistry, ensureRegistry as ensureCloudClusterRegistry } from './cloudCluster/registry.js';
import {
  createCluster as createCloudCluster,
  upsertFactoryObject as upsertCloudFactoryObject,
  removeFactoryObject as removeCloudFactoryObject,
  upsertLink as upsertCloudClusterLink,
  removeLink as removeCloudClusterLink,
  serialiseCluster,
} from './cloudCluster/domain/cluster.js';
import { updateClusterAccumulatorMembership } from './cloudCluster/sim/index.js';
import { getCloudClusterRegistry, setCloudClusterRegistry } from './cloudCluster/state/index.js';
import { computeOwnershipEntries, computeClusterIntents } from './factoryOwnership/transform/index.js';
import { CLOUD_CLUSTER_AUTO_LINK_PREFIX } from './factoryOwnership/constants.js';

export function createFactoryOwnershipManager({
  ensureFactoryState,
  factoryKindMeta,
  factoryItemLabel,
  getRecipeInputMap,
  getBioforgeRecipe,
  defaultBioforgeRecipe,
  getConstructorBlueprint,
  defaultConstructorBlueprint,
  FactoryKind,
}){
  function captureOwnershipInputs(factory){
    const worldSnapshot = {
      width: Number.isFinite(world?.W) ? world.W : 0,
      dominantFaction: world?.dominantFaction ?? [],
      controlLevel: world?.controlLevel ?? [],
    };

    const nodes = [];
    const nodesByTile = new Map();
    if(factory?.nodes instanceof Map){
      for(const [key, node] of factory.nodes.entries()){
        const tileIdx = Number(key);
        if(!Number.isFinite(tileIdx) || tileIdx < 0) continue;
        const nodeSnapshot = {
          tileIdx,
          resource: node?.resource ?? null,
        };
        nodes.push(nodeSnapshot);
        nodesByTile.set(tileIdx, nodeSnapshot);
      }
    }

    const structures = [];
    const structuresByTile = new Map();
    if(factory?.structures instanceof Map){
      for(const [key, structure] of factory.structures.entries()){
        const tileIdx = Number(key);
        if(!Number.isFinite(tileIdx) || tileIdx < 0) continue;
        const structureSnapshot = {
          tileIdx,
          kind: structure?.kind ?? null,
          orientation: structure?.orientation ?? null,
          recipeKey: structure?.recipeKey ?? null,
          availableRecipeKeys: Array.isArray(structure?.availableRecipeKeys) ? structure.availableRecipeKeys.slice() : null,
          activeRecipeIndex: typeof structure?.activeRecipeIndex === 'number' ? structure.activeRecipeIndex : null,
          blueprintKey: structure?.blueprintKey ?? null,
          availableBlueprintKeys: Array.isArray(structure?.availableBlueprintKeys) ? structure.availableBlueprintKeys.slice() : null,
        };
        structures.push(structureSnapshot);
        structuresByTile.set(tileIdx, structureSnapshot);
      }
    }

    return {
      world: worldSnapshot,
      nodes,
      structures,
      nodesByTile,
      structuresByTile,
      registrySnapshot: snapshotRegistry(factory),
    };
  }

  function ensureFactoryCloudRegistry(factory){
    const factoryRegistry = ensureCloudClusterRegistry(factory?.cloudClusters);
    const stateRegistry = getCloudClusterRegistry();
    const targetRegistry = stateRegistry;

    if(factoryRegistry !== stateRegistry){
      for(const [id, cluster] of factoryRegistry.byId.entries()){
        targetRegistry.byId.set(id, cluster);
        if(!targetRegistry.order.includes(id)){
          targetRegistry.order.push(id);
        }
      }
      const seen = new Set();
      targetRegistry.order = targetRegistry.order.filter((id) => {
        if(seen.has(id)) return false;
        seen.add(id);
        return true;
      });
    }

    if(factory){
      factory.cloudClusters = targetRegistry;
    }

    setCloudClusterRegistry(targetRegistry);
    return targetRegistry;
  }

  function snapshotRegistry(factory){
    const registry = ensureFactoryCloudRegistry(factory);
    const clustersById = new Map();
    for(const [id, cluster] of registry.byId.entries()){
      clustersById.set(id, serialiseCluster(cluster));
    }
    return { clustersById };
  }

  function clusterIdForFaction(factionId){
    return `faction-${factionId}-cloud`;
  }

  function clusterLabelForFaction(faction){
    if(!faction) return 'Faction Cloud';
    const key = faction.key ?? faction.id ?? '?';
    return `Faction ${key} Cloud`;
  }

  function ensureFactionCloudCluster(factory, faction, registry = ensureFactoryCloudRegistry(factory)){
    const clusterId = clusterIdForFaction(faction.id);
    let cluster = registry.byId.get(clusterId);
    if(!cluster){
      cluster = createCloudCluster({
        id: clusterId,
        name: clusterLabelForFaction(faction),
        description: `Autogenerated cluster for faction ${faction.key ?? faction.id}.`,
        metadata: {
          factionId: faction.id,
          factionKey: faction.key ?? null,
          auto: true,
        },
        objects: [],
        links: [],
      });
      registry.byId.set(clusterId, cluster);
    }
    if(!registry.order.includes(clusterId)){
      registry.order.push(clusterId);
    }
    return cluster;
  }

  function removeFactionCloudCluster(factory, factionId, registry = ensureFactoryCloudRegistry(factory)){
    const clusterId = clusterIdForFaction(factionId);
    if(!registry.byId.delete(clusterId)){
      return false;
    }
    const orderIndex = registry.order.indexOf(clusterId);
    if(orderIndex >= 0){
      registry.order.splice(orderIndex, 1);
    }
    return true;
  }

  function makeAutoLinkKey(link){
    if(!link) return '';
    const sourceId = link?.source?.objectId ?? '';
    const sourcePort = link?.source?.portId ?? '';
    const targetId = link?.target?.objectId ?? '';
    const targetPort = link?.target?.portId ?? '';
    const item = link?.metadata?.item ?? '';
    return `${sourceId}:${sourcePort}->${targetId}:${targetPort}:${item}`;
  }

  function applySmelterSelections(factory, selections){
    if(!factory || !Array.isArray(selections) || !selections.length){
      return;
    }
    if(!(factory.structures instanceof Map)){
      return;
    }
    for(const selection of selections){
      if(!selection || selection.tileIdx == null || !selection.nextRecipeKey){
        continue;
      }
      const structure = factory.structures.get(selection.tileIdx);
      if(!structure){
        continue;
      }
      const recipe = getBioforgeRecipe(selection.nextRecipeKey);
      if(!recipe){
        continue;
      }
      structure.recipe = recipe;
      structure.recipeKey = recipe.key;
      if(Array.isArray(structure.availableRecipeKeys)){
        const idx = structure.availableRecipeKeys.indexOf(recipe.key);
        if(idx >= 0){
          structure.activeRecipeIndex = idx;
        }
      }
    }
  }

  function updateFactionCluster(cluster, entries, factory, registry, ownershipInputs){
    const clustersById = ownershipInputs?.registrySnapshot?.clustersById;
    const clusterSnapshot = clustersById instanceof Map ? clustersById.get(cluster.id) : cluster;
    const intents = computeClusterIntents({
      clusterId: cluster.id,
      entries,
      ownershipInputs,
      clusterSnapshot,
      dependencies: {
        factoryKindMeta,
        factoryItemLabel,
        getRecipeInputMap,
        getBioforgeRecipe,
        defaultBioforgeRecipe,
        getConstructorBlueprint,
        defaultConstructorBlueprint,
        FactoryKind,
      },
    });

    applySmelterSelections(factory, intents.smelterSelections);

    const desiredObjects = intents.desiredObjects instanceof Map ? intents.desiredObjects : new Map();
    const desiredAutoLinks = intents.desiredAutoLinks instanceof Map ? intents.desiredAutoLinks : new Map();

    const removed = [];
    for(const objectId of Array.from(cluster.objects.keys())){
      if(desiredObjects.has(objectId)) continue;
      const existing = cluster.objects.get(objectId);
      const autoManaged = existing?.metadata?.auto === true;
      if(!autoManaged){
        continue;
      }
      removeCloudFactoryObject(cluster, objectId);
      removed.push(objectId);
    }

    const added = [];
    for(const [objectId, def] of desiredObjects.entries()){
      const existed = cluster.objects.has(objectId);
      upsertCloudFactoryObject(cluster, def);
      if(!existed){
        added.push(objectId);
      }
    }

    if(added.length || removed.length){
      updateClusterAccumulatorMembership(cluster.id, { added, removed });
    }

    const existingAutoLinks = new Map();
    for(const [linkId, link] of cluster.links.entries()){
      const isAuto = link?.metadata?.auto === true || (typeof linkId === 'string' && linkId.startsWith(CLOUD_CLUSTER_AUTO_LINK_PREFIX));
      if(!isAuto) continue;
      const key = makeAutoLinkKey(link);
      existingAutoLinks.set(key, linkId);
    }

    let linksChanged = false;

    for(const [key, linkId] of existingAutoLinks.entries()){
      if(desiredAutoLinks.has(key)){
        continue;
      }
      removeCloudClusterLink(cluster, linkId);
      linksChanged = true;
    }

    for(const [key, def] of desiredAutoLinks.entries()){
      if(existingAutoLinks.has(key)){
        continue;
      }
      upsertCloudClusterLink(cluster, def);
      linksChanged = true;
    }

    if(registry && (added.length || removed.length || linksChanged)){
      setCloudClusterRegistry(registry);
    }
  }

  function syncFactionCloudClusters(factory, ownershipByFaction, ownershipInputs){
    if(!factory) return;
    const registry = ensureFactoryCloudRegistry(factory);
    if(!(ownershipByFaction instanceof Map)){
      ownershipByFaction = factory.ownershipByFaction instanceof Map ? factory.ownershipByFaction : new Map();
    }
    for(const faction of FACTIONS){
      const clusterId = clusterIdForFaction(faction.id);
      const entries = ownershipByFaction.get(faction.id) ?? [];
      let cluster = registry.byId.get(clusterId);
      if(entries.length > 0){
        cluster = ensureFactionCloudCluster(factory, faction, registry);
        updateFactionCluster(cluster, entries, factory, registry, ownershipInputs);
        continue;
      }
      if(!cluster) continue;
      updateFactionCluster(cluster, [], factory, registry, ownershipInputs);
      const hasObjects = (cluster.objects?.size ?? 0) > 0;
      const hasLinks = (cluster.links?.size ?? 0) > 0;
      if(!hasObjects && !hasLinks){
        removeFactionCloudCluster(factory, faction.id, registry);
      }
    }
  }

  function refreshFactoryOwnership(){
    const factory = ensureFactoryState();
    const snapshot = captureOwnershipInputs(factory);
    const { entries, byFaction, unassigned } = computeOwnershipEntries(snapshot);

    factory.ownershipRecords = entries;
    factory.ownershipByFaction = byFaction;
    factory.unassignedOwnership = unassigned;
    syncFactionCloudClusters(factory, byFaction, snapshot);
  }

  function cloneOwnershipEntry(entry){
    if(!entry) return null;
    const clone = {
      id: entry.id,
      tileIdx: entry.tileIdx,
      type: entry.type,
      kind: entry.kind,
      control: entry.control,
      factionId: entry.factionId,
      dominantFactionId: entry.dominantFactionId ?? null,
    };
    if(entry.coords){
      clone.coords = { ...entry.coords };
    }
    if(entry.resource != null) clone.resource = entry.resource;
    if(entry.orientation != null) clone.orientation = entry.orientation;
    return clone;
  }

  function getFactoryOwnership(){
    refreshFactoryOwnership();
    const factory = ensureFactoryState();
    const byFactionMap = factory.ownershipByFaction instanceof Map ? factory.ownershipByFaction : new Map();
    const allEntries = Array.isArray(factory.ownershipRecords) ? factory.ownershipRecords : [];
    const unassigned = Array.isArray(factory.unassignedOwnership) ? factory.unassignedOwnership : [];
    const byFaction = FACTIONS.map((faction) => ({
      factionId: faction.id,
      factionKey: faction.key,
      color: faction.color,
      objects: (byFactionMap.get(faction.id) ?? []).map(cloneOwnershipEntry).filter(Boolean),
    }));
    return {
      byFaction,
      unassigned: unassigned.map(cloneOwnershipEntry).filter(Boolean),
      all: allEntries.map(cloneOwnershipEntry).filter(Boolean),
    };
  }

  return {
    refreshFactoryOwnership,
    getFactoryOwnership,
    ensureFactoryCloudRegistry,
  };
}

export function initialiseFactoryOwnership(factory){
  const registry = ensureCloudClusterRegistry(factory?.cloudClusters);
  if(factory){
    factory.cloudClusters = registry ?? createCloudClusterRegistry();
  }
  return registry;
}
